import { Palette, VerticalBox } from "std-widgets.slint";

export enum ItemType {
    A,
    B
}

export component ListItem inherits Rectangle {
    in property <string> text;
    in property <ItemType> type: ItemType.A;
    height: 50px;
    cm := ContextMenuArea {
        Menu {
            if type == ItemType.A: MenuItem {
                title: text + " - Menu 1";
            }

            if type == ItemType.B: MenuItem {
                title: text + " - Menu 2";
            }
        }
    }
    ta := TouchArea {
        pointer-event(ev) => {
            if ev.kind == PointerEventKind.up && (ev.button == PointerEventButton.right || ev.button == PointerEventButton.left) {
                cm.show({x: self.mouse-x, y: self.mouse-y});
            }
        }
    }
    Rectangle {
        border-width: 1px;
        border-color: Palette.border;
    }
    Text {
        text: text;
    }
}